// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Декларативный каталог достижений (ТЗ v2 §4). Одна запись = одно достижение:
 * код, группа, иконка, редкость, скрытость, ключ метрики, уровни
 * (бронза/серебро/золото) и тексты ru+en. Логика выдачи — это набор функций-
 * метрик на стороне API (metric key → число по userId); новое достижение на
 * существующей метрике добавляется ОДНОЙ строкой ниже, без правки логики.
 * Новая метрика — это новый ключ в ACHIEVEMENT_METRICS + функция в API.
 *
 * Тексты: ключи i18n `achievements.<код>.title|description`, значения берутся
 * из этой же записи (веб подмешивает их в словарь через achievementMessages).
 * В описании `{n}` заменяется порогом уровня.
 */

/* ----- Метрики и события ----- */

/** События, после которых пересчитываются связанные метрики. */
export const ACHIEVEMENT_EVENTS = [
  'checkin',
  'transaction',
  'budget',
  'reconciliation',
  'import',
  'goal',
  'habit',
  'account',
] as const;
export type AchievementEvent = (typeof ACHIEVEMENT_EVENTS)[number];

const ALL_EVENTS = ACHIEVEMENT_EVENTS;

/**
 * Ключи метрик → события, после которых метрика может измениться. Для каждого
 * ключа в API есть функция вычисления (проверяется типом Record и тестом).
 */
export const ACHIEVEMENT_METRIC_EVENTS = {
  // Чек-ины
  checkin_count: ['checkin'],
  checkin_days: ['checkin'],
  checkin_streak_best: ['checkin'],
  checkin_full_count: ['checkin'],
  checkin_note_count: ['checkin'],
  checkin_tag_count: ['checkin'],
  checkin_summary_count: ['checkin'],
  checkin_energy_count: ['checkin'],
  checkin_stress_count: ['checkin'],
  checkin_water_days: ['checkin'],
  checkin_steps_days: ['checkin'],
  checkin_sleep_days: ['checkin'],
  checkin_morning_count: ['checkin'],
  checkin_evening_count: ['checkin'],
  checkin_both_slots_days: ['checkin'],
  checkin_high_mood_count: ['checkin'],
  checkin_weekend_days: ['checkin'],
  checkin_goal_weeks: ['checkin'],
  checkin_tag_distinct: ['checkin'],
  checkin_note_chars: ['checkin'],
  checkin_water_total: ['checkin'],
  checkin_steps_total: ['checkin'],
  checkin_sleep_avg_x10: ['checkin'],
  checkin_mood_avg_x10: ['checkin'],
  checkin_energy_avg_x10: ['checkin'],
  checkin_calm_count: ['checkin'],
  checkin_energized_count: ['checkin'],
  checkin_late_count: ['checkin'],
  checkin_double_days: ['checkin'],
  checkin_full_streak_best: ['checkin'],
  checkin_perfect_weeks: ['checkin'],
  checkin_water_streak_best: ['checkin'],
  checkin_steps_streak_best: ['checkin'],
  checkin_sleep_streak_best: ['checkin'],
  checkin_monday_days: ['checkin'],
  checkin_tuesday_days: ['checkin'],
  checkin_wednesday_days: ['checkin'],
  checkin_thursday_days: ['checkin'],
  checkin_friday_days: ['checkin'],
  checkin_saturday_days: ['checkin'],
  checkin_sunday_days: ['checkin'],
  special_midnight_checkins: ['checkin'],
  special_early_checkins: ['checkin'],
  special_new_year_checkin: ['checkin'],
  special_leap_day_checkin: ['checkin'],
  special_friday13_checkin: ['checkin'],
  special_month_start_checkin: ['checkin'],
  special_month_end_checkin: ['checkin'],
  special_palindrome_checkin: ['checkin'],
  special_halloween_checkin: ['checkin'],
  mood_comeback_count: ['checkin'],
  // Финансы
  transaction_count: ['transaction', 'import'],
  income_count: ['transaction', 'import'],
  expense_count: ['transaction', 'import'],
  transfer_count: ['transaction', 'import'],
  transaction_days: ['transaction', 'import'],
  transaction_streak_best: ['transaction', 'import'],
  transaction_comment_count: ['transaction', 'import'],
  transaction_long_comment_count: ['transaction', 'import'],
  transaction_max_amount: ['transaction', 'import'],
  transaction_round_count: ['transaction', 'import'],
  transaction_weekend_count: ['transaction', 'import'],
  transaction_distinct_months: ['transaction', 'import'],
  category_used_count: ['transaction', 'import'],
  currency_count: ['transaction', 'account', 'import'],
  expense_total_base: ['transaction', 'import'],
  income_total_base: ['transaction', 'import'],
  savings_rate_best: ['transaction', 'import'],
  net_positive_months: ['transaction', 'import'],
  account_count: ['account'],
  account_type_count: ['account'],
  budget_count: ['budget'],
  budget_category_count: ['budget'],
  budget_closed_months: ['budget', 'transaction', 'import'],
  budget_closed_streak_best: ['budget', 'transaction', 'import'],
  budget_under80_months: ['budget', 'transaction', 'import'],
  reconciliation_count: ['reconciliation', 'import'],
  reconciliation_account_count: ['reconciliation', 'import'],
  reconciliation_statement_count: ['import', 'reconciliation'],
  reconciliation_matched_accounts: ['reconciliation', 'import', 'transaction'],
  reconciliation_source_count: ['reconciliation', 'import'],
  import_transaction_count: ['import'],
  import_days: ['import'],
  // Накопления
  goal_count: ['goal'],
  goal_best_percent: ['goal'],
  goal_completed_count: ['goal'],
  goal_deposit_count: ['goal'],
  goal_deposit_days: ['goal'],
  goal_active_count: ['goal'],
  goal_saved_total: ['goal'],
  // Привычки
  habit_count: ['habit'],
  habit_log_count: ['habit'],
  habit_active_days: ['habit'],
  habit_best_streak: ['habit'],
  habit_multi_days: ['habit'],
  habit_active_count: ['habit'],
  habit_week_count: ['habit'],
  habit_month_count: ['habit'],
  // Активность (зависят от любых событий)
  active_days: ALL_EVENTS,
  active_streak_best: ALL_EVENTS,
  active_modules: ALL_EVENTS,
  account_age_days: ALL_EVENTS,
  account_age_months: ALL_EVENTS,
  perfect_days: ALL_EVENTS,
  active_weekday_count: ALL_EVENTS,
  active_month_count: ALL_EVENTS,
  active_weekend_days: ALL_EVENTS,
} as const satisfies Record<string, readonly AchievementEvent[]>;

export type AchievementMetric = keyof typeof ACHIEVEMENT_METRIC_EVENTS;
export const ACHIEVEMENT_METRICS = Object.keys(ACHIEVEMENT_METRIC_EVENTS) as AchievementMetric[];

/** Метрики, которые могли измениться после события. */
export function metricsForEvent(event: AchievementEvent): AchievementMetric[] {
  return ACHIEVEMENT_METRICS.filter((metric) =>
    (ACHIEVEMENT_METRIC_EVENTS[metric] as readonly AchievementEvent[]).includes(event),
  );
}

/* ----- Типы каталога ----- */

export const ACHIEVEMENT_GROUPS = ['checkin', 'finance', 'activity', 'special'] as const;
export type AchievementGroup = (typeof ACHIEVEMENT_GROUPS)[number];

export const ACHIEVEMENT_RARITIES = ['common', 'rare', 'epic', 'legendary'] as const;
export type AchievementRarity = (typeof ACHIEVEMENT_RARITIES)[number];

export const ACHIEVEMENT_LEVELS = ['bronze', 'silver', 'gold'] as const;
export type AchievementLevel = (typeof ACHIEVEMENT_LEVELS)[number];

export interface AchievementTier {
  level: AchievementLevel;
  threshold: number;
}

export type AchievementCode = string;

export interface AchievementDefinition {
  code: AchievementCode;
  group: AchievementGroup;
  /** Ключ метрики: число, с которым сравниваются пороги уровней. */
  metric: AchievementMetric;
  icon: string;
  rarity: AchievementRarity;
  /** Скрытое: до получения в UI показывается как «???». */
  hidden: boolean;
  /** Уровни по возрастанию порога; одноуровневое — один «gold». */
  tiers: readonly AchievementTier[];
  titleKey: string;
  descriptionKey: string;
  /** Порядок показа внутри группы (индекс в каталоге). */
  position: number;
}

export interface AchievementText {
  title: string;
  description: string;
}

type Locale = 'ru' | 'en';

const LEVEL_SETS: Record<number, readonly AchievementLevel[]> = {
  1: ['gold'],
  2: ['silver', 'gold'],
  3: ['bronze', 'silver', 'gold'],
};

interface Row {
  code: string;
  group: AchievementGroup;
  metric: AchievementMetric;
  icon: string;
  rarity: AchievementRarity;
  thresholds: readonly number[];
  ru: readonly [title: string, description: string];
  en: readonly [title: string, description: string];
  hidden?: boolean;
}

const C = 'common';
const R = 'rare';
const E = 'epic';
const L = 'legendary';

/* ----- Каталог: одна строка — одно достижение ----- */

const ROWS: readonly Row[] = [
  // ===== Чек-ины =====
  {
    code: 'checkin_total',
    group: 'checkin',
    metric: 'checkin_count',
    icon: '🌱',
    rarity: C,
    thresholds: [1, 30, 100],
    ru: ['Первый шаг', 'Чек-инов за всё время: {n}.'],
    en: ['First step', 'Check-ins in total: {n}.'],
  },
  {
    code: 'checkin_streak',
    group: 'checkin',
    metric: 'checkin_streak_best',
    icon: '🔥',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Серия чек-инов', 'Дней с чек-инами подряд: {n}.'],
    en: ['Check-in streak', 'Check-in days in a row: {n}.'],
  },
  {
    code: 'checkin_days',
    group: 'checkin',
    metric: 'checkin_days',
    icon: '📅',
    rarity: C,
    thresholds: [7, 60, 365],
    ru: ['Дни с самочувствием', 'Разных дней с чек-ином: {n}.'],
    en: ['Days of wellbeing', 'Different days with a check-in: {n}.'],
  },
  {
    code: 'checkin_full',
    group: 'checkin',
    metric: 'checkin_full_count',
    icon: '🧩',
    rarity: R,
    thresholds: [1, 20, 100],
    ru: ['Полная картина', 'Чек-инов со всеми полями (энергия, стресс, сон, вода, шаги): {n}.'],
    en: ['Full picture', 'Check-ins with every field (energy, stress, sleep, water, steps): {n}.'],
  },
  {
    code: 'checkin_notes',
    group: 'checkin',
    metric: 'checkin_note_count',
    icon: '✍️',
    rarity: C,
    thresholds: [5, 30, 100],
    ru: ['Дневник мыслей', 'Чек-инов с заметкой: {n}.'],
    en: ['Thought diary', 'Check-ins with a note: {n}.'],
  },
  {
    code: 'checkin_tags',
    group: 'checkin',
    metric: 'checkin_tag_count',
    icon: '🏷️',
    rarity: C,
    thresholds: [5, 30, 100],
    ru: ['Мастер тегов', 'Чек-инов с тегами: {n}.'],
    en: ['Tag master', 'Check-ins with tags: {n}.'],
  },
  {
    code: 'checkin_summary',
    group: 'checkin',
    metric: 'checkin_summary_count',
    icon: '🌙',
    rarity: C,
    thresholds: [3, 20, 60],
    ru: ['Итог дня', 'Вечерних итогов дня: {n}.'],
    en: ['Day wrap-up', 'Evening day summaries: {n}.'],
  },
  {
    code: 'checkin_energy',
    group: 'checkin',
    metric: 'checkin_energy_count',
    icon: '⚡',
    rarity: C,
    thresholds: [10, 50, 200],
    ru: ['Заряд энергии', 'Чек-инов с оценкой энергии: {n}.'],
    en: ['Energy charge', 'Check-ins with an energy rating: {n}.'],
  },
  {
    code: 'checkin_stress',
    group: 'checkin',
    metric: 'checkin_stress_count',
    icon: '🧘',
    rarity: C,
    thresholds: [10, 50, 200],
    ru: ['Под контролем', 'Чек-инов с оценкой стресса: {n}.'],
    en: ['Under control', 'Check-ins with a stress rating: {n}.'],
  },
  {
    code: 'water_days',
    group: 'checkin',
    metric: 'checkin_water_days',
    icon: '💧',
    rarity: C,
    thresholds: [5, 30, 100],
    ru: ['Водный баланс', 'Дней с 8 и более стаканами воды: {n}.'],
    en: ['Water balance', 'Days with 8 or more glasses of water: {n}.'],
  },
  {
    code: 'steps_days',
    group: 'checkin',
    metric: 'checkin_steps_days',
    icon: '👟',
    rarity: R,
    thresholds: [5, 30, 100],
    ru: ['Десять тысяч шагов', 'Дней с 10 000 шагов и более: {n}.'],
    en: ['Ten thousand steps', 'Days with 10,000 steps or more: {n}.'],
  },
  {
    code: 'sleep_days',
    group: 'checkin',
    metric: 'checkin_sleep_days',
    icon: '😴',
    rarity: R,
    thresholds: [5, 30, 100],
    ru: ['Здоровый сон', 'Дней со сном 7–9 часов: {n}.'],
    en: ['Healthy sleep', 'Days with 7–9 hours of sleep: {n}.'],
  },
  {
    code: 'morning_checkins',
    group: 'checkin',
    metric: 'checkin_morning_count',
    icon: '🌅',
    rarity: C,
    thresholds: [5, 30, 100],
    ru: ['Утренний ритуал', 'Утренних чек-инов: {n}.'],
    en: ['Morning ritual', 'Morning check-ins: {n}.'],
  },
  {
    code: 'evening_checkins',
    group: 'checkin',
    metric: 'checkin_evening_count',
    icon: '🌇',
    rarity: C,
    thresholds: [5, 30, 100],
    ru: ['Вечерний ритуал', 'Вечерних чек-инов: {n}.'],
    en: ['Evening ritual', 'Evening check-ins: {n}.'],
  },
  {
    code: 'both_slots',
    group: 'checkin',
    metric: 'checkin_both_slots_days',
    icon: '☯️',
    rarity: R,
    thresholds: [3, 15, 60],
    ru: ['Утро и вечер', 'Дней с утренним и вечерним чек-ином: {n}.'],
    en: ['Morning and evening', 'Days with both a morning and an evening check-in: {n}.'],
  },
  {
    code: 'high_mood',
    group: 'checkin',
    metric: 'checkin_high_mood_count',
    icon: '😄',
    rarity: C,
    thresholds: [5, 30, 100],
    ru: ['Отличное настроение', 'Чек-инов с настроением 5 из 5: {n}.'],
    en: ['Great mood', 'Check-ins with mood 5 out of 5: {n}.'],
  },
  {
    code: 'weekend_checkins',
    group: 'checkin',
    metric: 'checkin_weekend_days',
    icon: '🏖️',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['Выходные с Пульсом', 'Выходных дней с чек-ином: {n}.'],
    en: ['Weekends with Pulse', 'Weekend days with a check-in: {n}.'],
  },
  {
    code: 'weekly_goal',
    group: 'checkin',
    metric: 'checkin_goal_weeks',
    icon: '🎯',
    rarity: R,
    thresholds: [1, 4, 12],
    ru: ['Цель недели', 'Недель, когда выполнена цель по чек-инам: {n}.'],
    en: ['Weekly goal', 'Weeks when the check-in goal was met: {n}.'],
  },

  // ===== Финансы: операции =====
  {
    code: 'transactions_total',
    group: 'finance',
    metric: 'transaction_count',
    icon: '🧾',
    rarity: C,
    thresholds: [1, 100, 1000],
    ru: ['Первая запись', 'Операций в дневнике: {n}.'],
    en: ['First entry', 'Transactions logged: {n}.'],
  },
  {
    code: 'expense_entries',
    group: 'finance',
    metric: 'expense_count',
    icon: '🛒',
    rarity: C,
    thresholds: [10, 100, 500],
    ru: ['Учёт расходов', 'Записано расходов: {n}.'],
    en: ['Expense tracking', 'Expenses logged: {n}.'],
  },
  {
    code: 'income_entries',
    group: 'finance',
    metric: 'income_count',
    icon: '💰',
    rarity: C,
    thresholds: [1, 12, 60],
    ru: ['Доходы на виду', 'Записано доходов: {n}.'],
    en: ['Income in sight', 'Incomes logged: {n}.'],
  },
  {
    code: 'transfer_entries',
    group: 'finance',
    metric: 'transfer_count',
    icon: '🔁',
    rarity: C,
    thresholds: [1, 10, 50],
    ru: ['Между счетами', 'Переводов между счетами: {n}.'],
    en: ['Between accounts', 'Transfers between accounts: {n}.'],
  },
  {
    code: 'transaction_days',
    group: 'finance',
    metric: 'transaction_days',
    icon: '🗓️',
    rarity: C,
    thresholds: [7, 60, 200],
    ru: ['Учёт без пропусков', 'Дней с записанными операциями: {n}.'],
    en: ['Steady bookkeeping', 'Days with logged transactions: {n}.'],
  },
  {
    code: 'transaction_streak',
    group: 'finance',
    metric: 'transaction_streak_best',
    icon: '📈',
    rarity: R,
    thresholds: [3, 14, 60],
    ru: ['Серия учёта', 'Дней подряд с записанными операциями: {n}.'],
    en: ['Bookkeeping streak', 'Days in a row with logged transactions: {n}.'],
  },
  {
    code: 'transaction_comments',
    group: 'finance',
    metric: 'transaction_comment_count',
    icon: '💬',
    rarity: C,
    thresholds: [10, 50, 200],
    ru: ['С комментарием', 'Операций с комментарием: {n}.'],
    en: ['With a comment', 'Transactions with a comment: {n}.'],
  },
  {
    code: 'categories_used',
    group: 'finance',
    metric: 'category_used_count',
    icon: '🗂️',
    rarity: C,
    thresholds: [5, 10, 20],
    ru: ['Всё по полочкам', 'Разных категорий в операциях: {n}.'],
    en: ['Neatly sorted', 'Different categories used: {n}.'],
  },
  {
    code: 'multi_currency',
    group: 'finance',
    metric: 'currency_count',
    icon: '🌍',
    rarity: R,
    thresholds: [2, 3, 5],
    ru: ['Мультивалютный', 'Разных валют в счетах и операциях: {n}.'],
    en: ['Multi-currency', 'Different currencies in accounts and transactions: {n}.'],
  },
  {
    code: 'accounts_total',
    group: 'finance',
    metric: 'account_count',
    icon: '🏦',
    rarity: C,
    thresholds: [2, 3, 5],
    ru: ['Несколько счетов', 'Счетов в Пульсе: {n}.'],
    en: ['Several accounts', 'Accounts in Pulse: {n}.'],
  },
  // ===== Финансы: бюджеты =====
  {
    code: 'budgets_set',
    group: 'finance',
    metric: 'budget_count',
    icon: '📋',
    rarity: C,
    thresholds: [1, 6, 24],
    ru: ['Бюджетник', 'Бюджетов по категориям: {n}.'],
    en: ['Budgeteer', 'Category budgets set: {n}.'],
  },
  {
    code: 'budget_categories',
    group: 'finance',
    metric: 'budget_category_count',
    icon: '🎛️',
    rarity: C,
    thresholds: [3, 5, 10],
    ru: ['Всё под контролем', 'Категорий с бюджетом: {n}.'],
    en: ['Everything under control', 'Categories with a budget: {n}.'],
  },
  {
    code: 'budget_closed',
    group: 'finance',
    metric: 'budget_closed_months',
    icon: '📊',
    rarity: R,
    thresholds: [1, 3, 12],
    ru: ['В рамках бюджета', 'Месяцев закрыто без превышения бюджета: {n}.'],
    en: ['Within budget', 'Months closed without exceeding the budget: {n}.'],
  },
  {
    code: 'budget_streak',
    group: 'finance',
    metric: 'budget_closed_streak_best',
    icon: '🛡️',
    rarity: E,
    thresholds: [2, 4, 6],
    ru: ['Финансовая дисциплина', 'Месяцев подряд без превышения бюджета: {n}.'],
    en: ['Financial discipline', 'Months in a row without exceeding the budget: {n}.'],
  },
  // ===== Финансы: сверка и импорт =====
  {
    code: 'reconciliations',
    group: 'finance',
    metric: 'reconciliation_count',
    icon: '⚖️',
    rarity: C,
    thresholds: [1, 5, 20],
    ru: ['Сверка баланса', 'Сверок с данными банка: {n}.'],
    en: ['Balance check', 'Reconciliations with bank data: {n}.'],
  },
  {
    code: 'reconciled_accounts',
    group: 'finance',
    metric: 'reconciliation_account_count',
    icon: '🔍',
    rarity: R,
    thresholds: [1, 3, 5],
    ru: ['Счета сверены', 'Счетов, сверенных с банком: {n}.'],
    en: ['Accounts reconciled', 'Accounts reconciled with the bank: {n}.'],
  },
  {
    code: 'statement_imports',
    group: 'finance',
    metric: 'reconciliation_statement_count',
    icon: '📥',
    rarity: C,
    thresholds: [1, 5, 20],
    ru: ['Выписка загружена', 'Загружено выписок: {n}.'],
    en: ['Statement uploaded', 'Statements uploaded: {n}.'],
  },
  {
    code: 'imported_rows',
    group: 'finance',
    metric: 'import_transaction_count',
    icon: '📦',
    rarity: R,
    thresholds: [10, 200, 2000],
    ru: ['Большой импорт', 'Операций, импортированных из выписок: {n}.'],
    en: ['Big import', 'Transactions imported from statements: {n}.'],
  },
  {
    code: 'balance_match',
    group: 'finance',
    metric: 'reconciliation_matched_accounts',
    icon: '🎯',
    rarity: E,
    thresholds: [1, 3, 5],
    hidden: true,
    ru: ['Копейка в копейку', 'Счетов, где баланс сошёлся с банком: {n}.'],
    en: ['Penny perfect', 'Accounts whose balance matches the bank: {n}.'],
  },
  // ===== Финансы: накопления =====
  {
    code: 'goals_created',
    group: 'finance',
    metric: 'goal_count',
    icon: '🎯',
    rarity: C,
    thresholds: [1, 3, 10],
    ru: ['Первый ориентир', 'Целей накопления создано: {n}.'],
    en: ['First milestone', 'Savings goals created: {n}.'],
  },
  {
    code: 'goal_progress',
    group: 'finance',
    metric: 'goal_best_percent',
    icon: '⛰️',
    rarity: R,
    thresholds: [25, 50, 100],
    ru: ['Путь к цели', 'Лучший прогресс по цели, %: {n}.'],
    en: ['Road to the goal', 'Best goal progress, %: {n}.'],
  },
  {
    code: 'goals_completed',
    group: 'finance',
    metric: 'goal_completed_count',
    icon: '🏆',
    rarity: E,
    thresholds: [1, 3, 10],
    ru: ['Цель достигнута', 'Достигнуто целей: {n}.'],
    en: ['Goal reached', 'Goals reached: {n}.'],
  },
  {
    code: 'goal_deposits',
    group: 'finance',
    metric: 'goal_deposit_count',
    icon: '🐷',
    rarity: C,
    thresholds: [1, 10, 50],
    ru: ['Копилка', 'Пополнений целей: {n}.'],
    en: ['Piggy bank', 'Goal deposits: {n}.'],
  },
  {
    code: 'goal_deposit_days',
    group: 'finance',
    metric: 'goal_deposit_days',
    icon: '💎',
    rarity: R,
    thresholds: [3, 15, 60],
    ru: ['Регулярные накопления', 'Дней с пополнением целей: {n}.'],
    en: ['Regular saving', 'Days with a goal deposit: {n}.'],
  },

  // ===== Активность =====
  {
    code: 'active_days',
    group: 'activity',
    metric: 'active_days',
    icon: '✨',
    rarity: C,
    thresholds: [7, 50, 200],
    ru: ['Дни с Пульсом', 'Дней активности в приложении: {n}.'],
    en: ['Days with Pulse', 'Days of activity in the app: {n}.'],
  },
  {
    code: 'active_streak',
    group: 'activity',
    metric: 'active_streak_best',
    icon: '🚀',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Серия активности', 'Дней активности подряд: {n}.'],
    en: ['Activity streak', 'Days of activity in a row: {n}.'],
  },
  {
    code: 'veteran',
    group: 'activity',
    metric: 'account_age_days',
    icon: '🎖️',
    rarity: R,
    thresholds: [30, 180, 365],
    ru: ['Старожил', 'Дней с момента регистрации: {n}.'],
    en: ['Veteran', 'Days since registration: {n}.'],
  },
  {
    code: 'all_rounder',
    group: 'activity',
    metric: 'active_modules',
    icon: '🧭',
    rarity: E,
    thresholds: [3, 5, 7],
    ru: [
      'Универсал',
      'Разделов, которыми вы пользуетесь (чек-ины, операции, бюджеты, цели, привычки, сверка, импорт): {n}.',
    ],
    en: [
      'All-rounder',
      'Sections in use (check-ins, transactions, budgets, goals, habits, reconciliation, import): {n}.',
    ],
  },
  {
    code: 'habits_created',
    group: 'activity',
    metric: 'habit_count',
    icon: '🌿',
    rarity: C,
    thresholds: [1, 3, 7],
    ru: ['Новая привычка', 'Привычек создано: {n}.'],
    en: ['New habit', 'Habits created: {n}.'],
  },
  {
    code: 'habit_marks',
    group: 'activity',
    metric: 'habit_log_count',
    icon: '✅',
    rarity: C,
    thresholds: [10, 100, 500],
    ru: ['Отметки привычек', 'Выполненных отметок привычек: {n}.'],
    en: ['Habit check-offs', 'Habit marks done: {n}.'],
  },
  {
    code: 'habit_days',
    group: 'activity',
    metric: 'habit_active_days',
    icon: '📆',
    rarity: C,
    thresholds: [7, 50, 200],
    ru: ['Дни привычек', 'Дней с выполненной привычкой: {n}.'],
    en: ['Habit days', 'Days with a habit done: {n}.'],
  },
  {
    code: 'habit_streak',
    group: 'activity',
    metric: 'habit_best_streak',
    icon: '🔗',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Цепочка привычки', 'Дней подряд с одной привычкой: {n}.'],
    en: ['Habit chain', 'Days in a row with a single habit: {n}.'],
  },
  {
    code: 'habit_multi',
    group: 'activity',
    metric: 'habit_multi_days',
    icon: '🎪',
    rarity: R,
    thresholds: [3, 20, 60],
    ru: ['Много дел сразу', 'Дней с тремя и более выполненными привычками: {n}.'],
    en: ['Many things at once', 'Days with three or more habits done: {n}.'],
  },

  // ===== Особые и скрытые =====
  {
    code: 'perfect_day',
    group: 'special',
    metric: 'perfect_days',
    icon: '🌟',
    rarity: E,
    thresholds: [1, 10, 50],
    ru: ['Идеальный день', 'Дней с полным чек-ином, операцией и привычкой: {n}.'],
    en: ['Perfect day', 'Days with a full check-in, a transaction and a habit: {n}.'],
  },
  {
    code: 'midnight_checkin',
    group: 'special',
    metric: 'special_midnight_checkins',
    icon: '🦉',
    rarity: R,
    thresholds: [1, 5, 20],
    hidden: true,
    ru: ['Полуночник', 'Чек-инов между 00:00 и 01:00: {n}.'],
    en: ['Night owl', 'Check-ins between 00:00 and 01:00: {n}.'],
  },
  {
    code: 'early_bird',
    group: 'special',
    metric: 'special_early_checkins',
    icon: '🐦',
    rarity: R,
    thresholds: [1, 5, 20],
    hidden: true,
    ru: ['Жаворонок', 'Чек-инов между 04:00 и 06:00: {n}.'],
    en: ['Early bird', 'Check-ins between 04:00 and 06:00: {n}.'],
  },
  {
    code: 'comeback',
    group: 'special',
    metric: 'mood_comeback_count',
    icon: '🌈',
    rarity: E,
    thresholds: [1, 5, 20],
    hidden: true,
    ru: ['Всё к лучшему', 'Раз, когда настроение выросло с 1–2 до 4–5: {n}.'],
    en: ['It gets better', 'Times your mood rose from 1–2 to 4–5: {n}.'],
  },
  {
    code: 'streak_365',
    group: 'special',
    metric: 'checkin_streak_best',
    icon: '👑',
    rarity: L,
    thresholds: [365],
    hidden: true,
    ru: ['Год без пропусков', 'Дней с чек-инами подряд: {n}.'],
    en: ['A year without gaps', 'Check-in days in a row: {n}.'],
  },
  {
    code: 'new_year',
    group: 'special',
    metric: 'special_new_year_checkin',
    icon: '🎄',
    rarity: E,
    thresholds: [1],
    hidden: true,
    ru: ['С Новым годом!', 'Чек-ин в первый день года.'],
    en: ['Happy New Year!', 'A check-in on the first day of the year.'],
  },
  {
    code: 'leap_day',
    group: 'special',
    metric: 'special_leap_day_checkin',
    icon: '🐸',
    rarity: L,
    thresholds: [1],
    hidden: true,
    ru: ['Редкий день', 'Чек-ин 29 февраля.'],
    en: ['Rare day', 'A check-in on February 29.'],
  },
  {
    code: 'streak_180',
    group: 'special',
    metric: 'checkin_streak_best',
    icon: '🏔️',
    rarity: E,
    thresholds: [180],
    hidden: true,
    ru: ['Полгода в ритме', 'Дней с чек-инами подряд: {n}.'],
    en: ['Half a year in rhythm', 'Check-in days in a row: {n}.'],
  },
  {
    code: 'centurion',
    group: 'special',
    metric: 'checkin_count',
    icon: '💯',
    rarity: L,
    thresholds: [1000],
    hidden: true,
    ru: ['Тысяча чек-инов', 'Чек-инов за всё время: {n}.'],
    en: ['A thousand check-ins', 'Check-ins in total: {n}.'],
  },

  // ===== Чек-ины: новые метрики =====
  {
    code: 'checkin_tag_variety',
    group: 'checkin',
    metric: 'checkin_tag_distinct',
    icon: '🎨',
    rarity: C,
    thresholds: [3, 8, 20],
    ru: ['Коллекция тегов', 'Разных тегов в чек-инах: {n}.'],
    en: ['Tag collection', 'Different tags used in check-ins: {n}.'],
  },
  {
    code: 'checkin_tag_spread',
    group: 'checkin',
    metric: 'checkin_tag_distinct',
    icon: '🌈',
    rarity: R,
    thresholds: [2, 6],
    ru: ['Тег на каждый случай', 'Разных тегов в чек-инах: {n}.'],
    en: ['A tag for everything', 'Different tags used in check-ins: {n}.'],
  },
  {
    code: 'checkin_words',
    group: 'checkin',
    metric: 'checkin_note_chars',
    icon: '📝',
    rarity: C,
    thresholds: [500, 5000, 20000],
    ru: ['Слово за словом', 'Символов в заметках: {n}.'],
    en: ['Word by word', 'Characters written in notes: {n}.'],
  },
  {
    code: 'checkin_essays',
    group: 'checkin',
    metric: 'checkin_note_chars',
    icon: '✒️',
    rarity: R,
    thresholds: [1000, 10000],
    ru: ['Много букв', 'Символов в заметках: {n}.'],
    en: ['Lots of letters', 'Characters written in notes: {n}.'],
  },
  {
    code: 'checkin_water_total',
    group: 'checkin',
    metric: 'checkin_water_total',
    icon: '🚰',
    rarity: C,
    thresholds: [50, 500, 2000],
    ru: ['Водные запасы', 'Всего стаканов воды отмечено: {n}.'],
    en: ['Water reserves', 'Total glasses of water logged: {n}.'],
  },
  {
    code: 'checkin_water_ocean',
    group: 'checkin',
    metric: 'checkin_water_total',
    icon: '🐋',
    rarity: R,
    thresholds: [1000, 5000],
    ru: ['Целый океан', 'Всего стаканов воды отмечено: {n}.'],
    en: ['A whole ocean', 'Total glasses of water logged: {n}.'],
  },
  {
    code: 'checkin_steps_total',
    group: 'checkin',
    metric: 'checkin_steps_total',
    icon: '🚶',
    rarity: C,
    thresholds: [100000, 1000000, 5000000],
    ru: ['Пеший путь', 'Всего шагов отмечено: {n}.'],
    en: ['On foot', 'Total steps logged: {n}.'],
  },
  {
    code: 'checkin_steps_marathon',
    group: 'checkin',
    metric: 'checkin_steps_total',
    icon: '🏃',
    rarity: R,
    thresholds: [250000, 2500000],
    ru: ['Марафонец', 'Всего шагов отмечено: {n}.'],
    en: ['Marathoner', 'Total steps logged: {n}.'],
  },
  {
    code: 'checkin_steps_million',
    group: 'checkin',
    metric: 'checkin_steps_total',
    icon: '🦿',
    rarity: L,
    thresholds: [10000000],
    ru: ['Десять миллионов шагов', 'Всего шагов отмечено: {n}.'],
    en: ['Ten million steps', 'Total steps logged: {n}.'],
  },
  {
    code: 'checkin_sleep_average',
    group: 'checkin',
    metric: 'checkin_sleep_avg_x10',
    icon: '😴',
    rarity: R,
    thresholds: [65, 75, 80],
    ru: ['Средний сон', 'Средний сон, часы ×10: {n}.'],
    en: ['Average sleep', 'Average sleep, hours ×10: {n}.'],
  },
  {
    code: 'checkin_sleep_steady',
    group: 'checkin',
    metric: 'checkin_sleep_avg_x10',
    icon: '🛏️',
    rarity: E,
    thresholds: [70, 78],
    ru: ['Ровный сон', 'Средний сон, часы ×10: {n}.'],
    en: ['Steady sleep', 'Average sleep, hours ×10: {n}.'],
  },
  {
    code: 'checkin_mood_average',
    group: 'checkin',
    metric: 'checkin_mood_avg_x10',
    icon: '🙂',
    rarity: C,
    thresholds: [35, 40, 45],
    ru: ['Среднее настроение', 'Среднее настроение ×10: {n}.'],
    en: ['Average mood', 'Average mood ×10: {n}.'],
  },
  {
    code: 'checkin_mood_high',
    group: 'checkin',
    metric: 'checkin_mood_avg_x10',
    icon: '😊',
    rarity: E,
    thresholds: [42, 46],
    ru: ['На позитиве', 'Среднее настроение ×10: {n}.'],
    en: ['On the bright side', 'Average mood ×10: {n}.'],
  },
  {
    code: 'checkin_energy_average',
    group: 'checkin',
    metric: 'checkin_energy_avg_x10',
    icon: '🔋',
    rarity: C,
    thresholds: [35, 40, 45],
    ru: ['Средняя энергия', 'Средняя энергия ×10: {n}.'],
    en: ['Average energy', 'Average energy ×10: {n}.'],
  },
  {
    code: 'checkin_energy_high',
    group: 'checkin',
    metric: 'checkin_energy_avg_x10',
    icon: '⚡',
    rarity: E,
    thresholds: [42, 46],
    ru: ['Заряжен', 'Средняя энергия ×10: {n}.'],
    en: ['Fully charged', 'Average energy ×10: {n}.'],
  },
  {
    code: 'checkin_calm_count',
    group: 'checkin',
    metric: 'checkin_calm_count',
    icon: '😌',
    rarity: C,
    thresholds: [10, 50, 200],
    ru: ['Спокойствие', 'Чек-инов со стрессом 1–2 из 5: {n}.'],
    en: ['Calm', 'Check-ins with stress 1–2 out of 5: {n}.'],
  },
  {
    code: 'checkin_calm_deep',
    group: 'checkin',
    metric: 'checkin_calm_count',
    icon: '🕊️',
    rarity: R,
    thresholds: [100, 300],
    ru: ['Безмятежность', 'Чек-инов со стрессом 1–2 из 5: {n}.'],
    en: ['Serenity', 'Check-ins with stress 1–2 out of 5: {n}.'],
  },
  {
    code: 'checkin_energized_count',
    group: 'checkin',
    metric: 'checkin_energized_count',
    icon: '🚀',
    rarity: C,
    thresholds: [10, 50, 200],
    ru: ['Полон сил', 'Чек-инов с энергией 4–5 из 5: {n}.'],
    en: ['Full of energy', 'Check-ins with energy 4–5 out of 5: {n}.'],
  },
  {
    code: 'checkin_energized_more',
    group: 'checkin',
    metric: 'checkin_energized_count',
    icon: '🌟',
    rarity: R,
    thresholds: [100, 300],
    ru: ['Энергия бьёт ключом', 'Чек-инов с энергией 4–5 из 5: {n}.'],
    en: ['Bursting with energy', 'Check-ins with energy 4–5 out of 5: {n}.'],
  },
  {
    code: 'checkin_night_shift',
    group: 'checkin',
    metric: 'checkin_late_count',
    icon: '🌃',
    rarity: R,
    thresholds: [1, 10, 50],
    hidden: true,
    ru: ['Ночная смена', 'Чек-инов после 22:00: {n}.'],
    en: ['Night shift', 'Check-ins after 22:00: {n}.'],
  },
  {
    code: 'checkin_night_legend',
    group: 'checkin',
    metric: 'checkin_late_count',
    icon: '🌌',
    rarity: L,
    thresholds: [100],
    hidden: true,
    ru: ['Хранитель ночи', 'Чек-инов после 22:00: {n}.'],
    en: ['Keeper of the night', 'Check-ins after 22:00: {n}.'],
  },
  {
    code: 'checkin_double_days',
    group: 'checkin',
    metric: 'checkin_double_days',
    icon: '🧮',
    rarity: C,
    thresholds: [1, 15, 50],
    ru: ['Дважды за день', 'Дней с двумя и более чек-инами: {n}.'],
    en: ['Twice a day', 'Days with two or more check-ins: {n}.'],
  },
  {
    code: 'checkin_double_master',
    group: 'checkin',
    metric: 'checkin_double_days',
    icon: '♾️',
    rarity: R,
    thresholds: [100],
    ru: ['Двойной поток', 'Дней с двумя и более чек-инами: {n}.'],
    en: ['Double flow', 'Days with two or more check-ins: {n}.'],
  },
  {
    code: 'checkin_full_streak',
    group: 'checkin',
    metric: 'checkin_full_streak_best',
    icon: '🧩',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Полная серия', 'Дней подряд с чек-ином со всеми полями: {n}.'],
    en: ['Full streak', 'Days in a row with a check-in with every field: {n}.'],
  },
  {
    code: 'checkin_full_streak_pro',
    group: 'checkin',
    metric: 'checkin_full_streak_best',
    icon: '💠',
    rarity: L,
    thresholds: [180],
    ru: ['Безупречная серия', 'Дней подряд с чек-ином со всеми полями: {n}.'],
    en: ['Flawless streak', 'Days in a row with a check-in with every field: {n}.'],
  },
  {
    code: 'checkin_perfect_weeks',
    group: 'checkin',
    metric: 'checkin_perfect_weeks',
    icon: '🗓️',
    rarity: E,
    thresholds: [1, 4, 12],
    ru: ['Идеальные недели', 'Недель с чек-ином каждый день: {n}.'],
    en: ['Perfect weeks', 'Weeks with a check-in every day: {n}.'],
  },
  {
    code: 'checkin_perfect_year',
    group: 'checkin',
    metric: 'checkin_perfect_weeks',
    icon: '📖',
    rarity: L,
    thresholds: [26, 52],
    ru: ['Год без пропусков', 'Недель с чек-ином каждый день: {n}.'],
    en: ['A year without gaps', 'Weeks with a check-in every day: {n}.'],
  },
  {
    code: 'checkin_water_streak',
    group: 'checkin',
    metric: 'checkin_water_streak_best',
    icon: '💧',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Водный ритм', 'Дней подряд с 8 и более стаканами воды: {n}.'],
    en: ['Water rhythm', 'Days in a row with 8 or more glasses of water: {n}.'],
  },
  {
    code: 'checkin_water_streak_pro',
    group: 'checkin',
    metric: 'checkin_water_streak_best',
    icon: '🌊',
    rarity: L,
    thresholds: [180],
    ru: ['Половодье', 'Дней подряд с 8 и более стаканами воды: {n}.'],
    en: ['High water', 'Days in a row with 8 or more glasses of water: {n}.'],
  },
  {
    code: 'checkin_steps_streak',
    group: 'checkin',
    metric: 'checkin_steps_streak_best',
    icon: '👟',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Шаговый ритм', 'Дней подряд с 10 000 и более шагов: {n}.'],
    en: ['Step rhythm', 'Days in a row with 10,000 steps or more: {n}.'],
  },
  {
    code: 'checkin_steps_streak_pro',
    group: 'checkin',
    metric: 'checkin_steps_streak_best',
    icon: '🥾',
    rarity: L,
    thresholds: [180],
    ru: ['Неутомимый ходок', 'Дней подряд с 10 000 и более шагов: {n}.'],
    en: ['Tireless walker', 'Days in a row with 10,000 steps or more: {n}.'],
  },
  {
    code: 'checkin_sleep_streak',
    group: 'checkin',
    metric: 'checkin_sleep_streak_best',
    icon: '🌙',
    rarity: R,
    thresholds: [7, 30, 100],
    ru: ['Сонный ритм', 'Дней подряд со сном 7–9 часов: {n}.'],
    en: ['Sleep rhythm', 'Days in a row with 7–9 hours of sleep: {n}.'],
  },
  {
    code: 'checkin_sleep_streak_pro',
    group: 'checkin',
    metric: 'checkin_sleep_streak_best',
    icon: '🛌',
    rarity: L,
    thresholds: [180],
    ru: ['Хранитель сна', 'Дней подряд со сном 7–9 часов: {n}.'],
    en: ['Guardian of sleep', 'Days in a row with 7–9 hours of sleep: {n}.'],
  },
  {
    code: 'checkin_monday_days',
    group: 'checkin',
    metric: 'checkin_monday_days',
    icon: '1️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По понедельникам', 'Понедельников с чек-ином: {n}.'],
    en: ['Mondays', 'Mondays with a check-in: {n}.'],
  },
  {
    code: 'checkin_tuesday_days',
    group: 'checkin',
    metric: 'checkin_tuesday_days',
    icon: '2️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По вторникам', 'Вторников с чек-ином: {n}.'],
    en: ['Tuesdays', 'Tuesdays with a check-in: {n}.'],
  },
  {
    code: 'checkin_wednesday_days',
    group: 'checkin',
    metric: 'checkin_wednesday_days',
    icon: '3️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По средам', 'Сред с чек-ином: {n}.'],
    en: ['Wednesdays', 'Wednesdays with a check-in: {n}.'],
  },
  {
    code: 'checkin_thursday_days',
    group: 'checkin',
    metric: 'checkin_thursday_days',
    icon: '4️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По четвергам', 'Четвергов с чек-ином: {n}.'],
    en: ['Thursdays', 'Thursdays with a check-in: {n}.'],
  },
  {
    code: 'checkin_friday_days',
    group: 'checkin',
    metric: 'checkin_friday_days',
    icon: '5️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По пятницам', 'Пятниц с чек-ином: {n}.'],
    en: ['Fridays', 'Fridays with a check-in: {n}.'],
  },
  {
    code: 'checkin_saturday_days',
    group: 'checkin',
    metric: 'checkin_saturday_days',
    icon: '6️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По субботам', 'Суббот с чек-ином: {n}.'],
    en: ['Saturdays', 'Saturdays with a check-in: {n}.'],
  },
  {
    code: 'checkin_sunday_days',
    group: 'checkin',
    metric: 'checkin_sunday_days',
    icon: '7️⃣',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['По воскресеньям', 'Воскресений с чек-ином: {n}.'],
    en: ['Sundays', 'Sundays with a check-in: {n}.'],
  },

  // ===== Финансы: новые метрики =====
  {
    code: 'expense_total',
    group: 'finance',
    metric: 'expense_total_base',
    icon: '💸',
    rarity: C,
    thresholds: [10000, 100000, 1000000],
    ru: ['Сумма расходов', 'Расходов в основной валюте: {n}.'],
    en: ['Total expenses', 'Expenses in the main currency: {n}.'],
  },
  {
    code: 'expense_big_turnover',
    group: 'finance',
    metric: 'expense_total_base',
    icon: '🏦',
    rarity: R,
    thresholds: [500000, 5000000],
    ru: ['Крупный оборот', 'Расходов в основной валюте: {n}.'],
    en: ['Big turnover', 'Expenses in the main currency: {n}.'],
  },
  {
    code: 'expense_legend',
    group: 'finance',
    metric: 'expense_total_base',
    icon: '🏛️',
    rarity: L,
    thresholds: [20000000],
    ru: ['Огромные траты', 'Расходов в основной валюте: {n}.'],
    en: ['Huge spending', 'Expenses in the main currency: {n}.'],
  },
  {
    code: 'income_total',
    group: 'finance',
    metric: 'income_total_base',
    icon: '💰',
    rarity: C,
    thresholds: [10000, 100000, 1000000],
    ru: ['Сумма доходов', 'Доходов в основной валюте: {n}.'],
    en: ['Total income', 'Income in the main currency: {n}.'],
  },
  {
    code: 'income_flow',
    group: 'finance',
    metric: 'income_total_base',
    icon: '🌊',
    rarity: R,
    thresholds: [500000, 5000000],
    ru: ['Денежный поток', 'Доходов в основной валюте: {n}.'],
    en: ['Cash flow', 'Income in the main currency: {n}.'],
  },
  {
    code: 'income_legend',
    group: 'finance',
    metric: 'income_total_base',
    icon: '💎',
    rarity: L,
    thresholds: [20000000],
    ru: ['Крупный капитал', 'Доходов в основной валюте: {n}.'],
    en: ['Big capital', 'Income in the main currency: {n}.'],
  },
  {
    code: 'savings_rate',
    group: 'finance',
    metric: 'savings_rate_best',
    icon: '🏧',
    rarity: E,
    thresholds: [10, 25, 40],
    ru: ['Норма сбережений', 'Лучшая доля сбережений за месяц, %: {n}.'],
    en: ['Savings rate', 'Best monthly savings share, %: {n}.'],
  },
  {
    code: 'savings_rate_pro',
    group: 'finance',
    metric: 'savings_rate_best',
    icon: '🥇',
    rarity: L,
    thresholds: [50],
    ru: ['Половина в копилку', 'Лучшая доля сбережений за месяц, %: {n}.'],
    en: ['Half into savings', 'Best monthly savings share, %: {n}.'],
  },
  {
    code: 'net_positive_months',
    group: 'finance',
    metric: 'net_positive_months',
    icon: '⬆️',
    rarity: R,
    thresholds: [1, 6, 12],
    ru: ['В плюсе', 'Месяцев, где доходы превысили расходы: {n}.'],
    en: ['In the black', 'Months where income exceeded expenses: {n}.'],
  },
  {
    code: 'net_positive_pro',
    group: 'finance',
    metric: 'net_positive_months',
    icon: '📈',
    rarity: E,
    thresholds: [24, 36],
    ru: ['Стабильный профицит', 'Месяцев, где доходы превысили расходы: {n}.'],
    en: ['Steady surplus', 'Months where income exceeded expenses: {n}.'],
  },
  {
    code: 'transaction_max',
    group: 'finance',
    metric: 'transaction_max_amount',
    icon: '💎',
    rarity: R,
    thresholds: [1000, 10000, 100000],
    ru: ['Крупная операция', 'Самая крупная операция в основной валюте: {n}.'],
    en: ['Big transaction', 'Largest transaction in the main currency: {n}.'],
  },
  {
    code: 'transaction_max_pro',
    group: 'finance',
    metric: 'transaction_max_amount',
    icon: '🐘',
    rarity: L,
    thresholds: [1000000],
    ru: ['Операция-гигант', 'Самая крупная операция в основной валюте: {n}.'],
    en: ['Giant transaction', 'Largest transaction in the main currency: {n}.'],
  },
  {
    code: 'round_payments',
    group: 'finance',
    metric: 'transaction_round_count',
    icon: '🔵',
    rarity: C,
    thresholds: [10, 100, 500],
    ru: ['Ровные суммы', 'Операций с суммой, кратной 100: {n}.'],
    en: ['Round amounts', 'Transactions with an amount divisible by 100: {n}.'],
  },
  {
    code: 'round_payments_pro',
    group: 'finance',
    metric: 'transaction_round_count',
    icon: '⭕',
    rarity: R,
    thresholds: [1000],
    ru: ['Всё круглое', 'Операций с суммой, кратной 100: {n}.'],
    en: ['All round', 'Transactions with an amount divisible by 100: {n}.'],
  },
  {
    code: 'weekend_transactions',
    group: 'finance',
    metric: 'transaction_weekend_count',
    icon: '🏖️',
    rarity: C,
    thresholds: [5, 50, 200],
    ru: ['Оплата в выходные', 'Операций в выходные дни: {n}.'],
    en: ['Weekend payments', 'Transactions on weekend days: {n}.'],
  },
  {
    code: 'weekend_transactions_pro',
    group: 'finance',
    metric: 'transaction_weekend_count',
    icon: '🎡',
    rarity: R,
    thresholds: [500],
    ru: ['Выходные — не повод', 'Операций в выходные дни: {n}.'],
    en: ['Weekends count too', 'Transactions on weekend days: {n}.'],
  },
  {
    code: 'transaction_months',
    group: 'finance',
    metric: 'transaction_distinct_months',
    icon: '🗓️',
    rarity: C,
    thresholds: [1, 12, 36],
    ru: ['Месяцы учёта', 'Месяцев с операциями: {n}.'],
    en: ['Months of bookkeeping', 'Months with transactions: {n}.'],
  },
  {
    code: 'transaction_months_pro',
    group: 'finance',
    metric: 'transaction_distinct_months',
    icon: '📚',
    rarity: E,
    thresholds: [60],
    ru: ['Финансовая история', 'Месяцев с операциями: {n}.'],
    en: ['Financial history', 'Months with transactions: {n}.'],
  },
  {
    code: 'account_types',
    group: 'finance',
    metric: 'account_type_count',
    icon: '🧾',
    rarity: C,
    thresholds: [2, 3, 5],
    ru: ['Разные типы счетов', 'Типов счетов: {n}.'],
    en: ['Different account types', 'Account types: {n}.'],
  },
  {
    code: 'account_types_pro',
    group: 'finance',
    metric: 'account_type_count',
    icon: '🗃️',
    rarity: R,
    thresholds: [6],
    ru: ['Целая коллекция счетов', 'Типов счетов: {n}.'],
    en: ['A whole collection of accounts', 'Account types: {n}.'],
  },
  {
    code: 'budget_under80',
    group: 'finance',
    metric: 'budget_under80_months',
    icon: '🎯',
    rarity: R,
    thresholds: [1, 3, 12],
    ru: ['Запас в бюджете', 'Месяцев с расходом до 80% лимита: {n}.'],
    en: ['Budget headroom', 'Months spending up to 80% of the limit: {n}.'],
  },
  {
    code: 'budget_under80_pro',
    group: 'finance',
    metric: 'budget_under80_months',
    icon: '🏹',
    rarity: E,
    thresholds: [24, 36],
    ru: ['Точный расчёт', 'Месяцев с расходом до 80% лимита: {n}.'],
    en: ['Precise planning', 'Months spending up to 80% of the limit: {n}.'],
  },
  {
    code: 'import_days',
    group: 'finance',
    metric: 'import_days',
    icon: '📥',
    rarity: C,
    thresholds: [1, 10, 50],
    ru: ['Дни импорта', 'Дней с импортированными операциями: {n}.'],
    en: ['Import days', 'Days with imported transactions: {n}.'],
  },
  {
    code: 'import_days_pro',
    group: 'finance',
    metric: 'import_days',
    icon: '📦',
    rarity: R,
    thresholds: [100, 365],
    ru: ['Поток выписок', 'Дней с импортированными операциями: {n}.'],
    en: ['Statement stream', 'Days with imported transactions: {n}.'],
  },
  {
    code: 'active_goals',
    group: 'finance',
    metric: 'goal_active_count',
    icon: '🎯',
    rarity: C,
    thresholds: [1, 3, 10],
    ru: ['Активные цели', 'Целей в работе: {n}.'],
    en: ['Active goals', 'Goals in progress: {n}.'],
  },
  {
    code: 'active_goals_pro',
    group: 'finance',
    metric: 'goal_active_count',
    icon: '🧗',
    rarity: R,
    thresholds: [20],
    ru: ['Много целей', 'Целей в работе: {n}.'],
    en: ['Many goals', 'Goals in progress: {n}.'],
  },
  {
    code: 'goals_saved',
    group: 'finance',
    metric: 'goal_saved_total',
    icon: '🐖',
    rarity: E,
    thresholds: [10000, 100000, 1000000],
    ru: ['Отложено всего', 'Накоплено по всем целям: {n}.'],
    en: ['Saved up in total', 'Saved across all goals: {n}.'],
  },
  {
    code: 'goals_saved_pro',
    group: 'finance',
    metric: 'goal_saved_total',
    icon: '🏆',
    rarity: L,
    thresholds: [5000000],
    ru: ['Крупная копилка', 'Накоплено по всем целям: {n}.'],
    en: ['Big piggy bank', 'Saved across all goals: {n}.'],
  },
  {
    code: 'reconciliation_sources',
    group: 'finance',
    metric: 'reconciliation_source_count',
    icon: '🔀',
    rarity: R,
    thresholds: [1, 2],
    ru: ['Разные источники сверки', 'Источников данных сверки: {n}.'],
    en: ['Several reconciliation sources', 'Reconciliation data sources: {n}.'],
  },
  {
    code: 'reconciliation_sources_pro',
    group: 'finance',
    metric: 'reconciliation_source_count',
    icon: '🗂️',
    rarity: E,
    thresholds: [3],
    ru: ['Все источники', 'Источников данных сверки: {n}.'],
    en: ['Every source', 'Reconciliation data sources: {n}.'],
  },
  {
    code: 'long_comments',
    group: 'finance',
    metric: 'transaction_long_comment_count',
    icon: '📝',
    rarity: R,
    thresholds: [1, 10, 50],
    ru: ['Развёрнутый комментарий', 'Операций с комментарием от 20 символов: {n}.'],
    en: ['Detailed comment', 'Transactions with a comment of 20+ characters: {n}.'],
  },
  {
    code: 'long_comments_pro',
    group: 'finance',
    metric: 'transaction_long_comment_count',
    icon: '📔',
    rarity: E,
    thresholds: [100, 500],
    ru: ['Дневник операций', 'Операций с комментарием от 20 символов: {n}.'],
    en: ['Transaction journal', 'Transactions with a comment of 20+ characters: {n}.'],
  },

  // ===== Активность: новые метрики =====
  {
    code: 'active_weekdays',
    group: 'activity',
    metric: 'active_weekday_count',
    icon: '📅',
    rarity: R,
    thresholds: [3, 5, 7],
    ru: ['Все дни недели', 'Дней недели, когда вы активны: {n}.'],
    en: ['Every day of the week', 'Days of the week when you are active: {n}.'],
  },
  {
    code: 'active_weekdays_pro',
    group: 'activity',
    metric: 'active_weekday_count',
    icon: '🧭',
    rarity: E,
    thresholds: [2, 4],
    ru: ['Почти всегда', 'Дней недели, когда вы активны: {n}.'],
    en: ['Almost always', 'Days of the week when you are active: {n}.'],
  },
  {
    code: 'active_months',
    group: 'activity',
    metric: 'active_month_count',
    icon: '🗓️',
    rarity: C,
    thresholds: [1, 6, 12],
    ru: ['Месяцы с Пульсом', 'Месяцев с активностью: {n}.'],
    en: ['Months with Pulse', 'Months with activity: {n}.'],
  },
  {
    code: 'active_months_pro',
    group: 'activity',
    metric: 'active_month_count',
    icon: '📆',
    rarity: E,
    thresholds: [24, 60],
    ru: ['Годы с Пульсом', 'Месяцев с активностью: {n}.'],
    en: ['Years with Pulse', 'Months with activity: {n}.'],
  },
  {
    code: 'active_weekends',
    group: 'activity',
    metric: 'active_weekend_days',
    icon: '🎡',
    rarity: C,
    thresholds: [4, 20, 52],
    ru: ['Активные выходные', 'Выходных дней с активностью: {n}.'],
    en: ['Active weekends', 'Weekend days with activity: {n}.'],
  },
  {
    code: 'active_weekends_pro',
    group: 'activity',
    metric: 'active_weekend_days',
    icon: '🎢',
    rarity: R,
    thresholds: [100, 260],
    ru: ['Все выходные — ваши', 'Выходных дней с активностью: {n}.'],
    en: ['Every weekend is yours', 'Weekend days with activity: {n}.'],
  },
  {
    code: 'habit_active',
    group: 'activity',
    metric: 'habit_active_count',
    icon: '🌱',
    rarity: C,
    thresholds: [1, 3, 7],
    ru: ['Привычки в деле', 'Привычек с хотя бы одной отметкой: {n}.'],
    en: ['Habits in action', 'Habits with at least one mark: {n}.'],
  },
  {
    code: 'habit_active_pro',
    group: 'activity',
    metric: 'habit_active_count',
    icon: '🌳',
    rarity: R,
    thresholds: [10],
    ru: ['Целый сад', 'Привычек с хотя бы одной отметкой: {n}.'],
    en: ['A whole garden', 'Habits with at least one mark: {n}.'],
  },
  {
    code: 'habit_weeks',
    group: 'activity',
    metric: 'habit_week_count',
    icon: '📆',
    rarity: R,
    thresholds: [1, 4, 12],
    ru: ['Недели привычек', 'Недель с отметками привычек: {n}.'],
    en: ['Habit weeks', 'Weeks with habit marks: {n}.'],
  },
  {
    code: 'habit_weeks_pro',
    group: 'activity',
    metric: 'habit_week_count',
    icon: '🔗',
    rarity: E,
    thresholds: [26, 52],
    ru: ['Год привычек', 'Недель с отметками привычек: {n}.'],
    en: ['A year of habits', 'Weeks with habit marks: {n}.'],
  },
  {
    code: 'habit_months',
    group: 'activity',
    metric: 'habit_month_count',
    icon: '🗓️',
    rarity: R,
    thresholds: [1, 6, 12],
    ru: ['Месяцы привычек', 'Месяцев с отметками привычек: {n}.'],
    en: ['Habit months', 'Months with habit marks: {n}.'],
  },
  {
    code: 'habit_months_pro',
    group: 'activity',
    metric: 'habit_month_count',
    icon: '📚',
    rarity: E,
    thresholds: [24, 60],
    ru: ['Привычная история', 'Месяцев с отметками привычек: {n}.'],
    en: ['A habitual history', 'Months with habit marks: {n}.'],
  },
  {
    code: 'account_age_months',
    group: 'activity',
    metric: 'account_age_months',
    icon: '🗓️',
    rarity: C,
    thresholds: [1, 6, 12],
    ru: ['Месяцы в Пульсе', 'Месяцев с момента регистрации: {n}.'],
    en: ['Months in Pulse', 'Months since registration: {n}.'],
  },
  {
    code: 'account_age_months_pro',
    group: 'activity',
    metric: 'account_age_months',
    icon: '🪙',
    rarity: E,
    thresholds: [24, 60],
    ru: ['Верность Пульсу', 'Месяцев с момента регистрации: {n}.'],
    en: ['Loyal to Pulse', 'Months since registration: {n}.'],
  },

  // ===== Особые: новые метрики =====
  {
    code: 'friday13',
    group: 'special',
    metric: 'special_friday13_checkin',
    icon: '🐈',
    rarity: L,
    thresholds: [1],
    hidden: true,
    ru: ['Пятница, 13-е', 'Чек-ин в пятницу 13-го.'],
    en: ['Friday the 13th', 'A check-in on Friday the 13th.'],
  },
  {
    code: 'month_start',
    group: 'special',
    metric: 'special_month_start_checkin',
    icon: '🌅',
    rarity: R,
    thresholds: [1, 3, 6],
    hidden: true,
    ru: ['Начало месяца', 'Чек-инов первого числа месяца: {n}.'],
    en: ['Start of the month', 'Check-ins on the first day of a month: {n}.'],
  },
  {
    code: 'month_start_pro',
    group: 'special',
    metric: 'special_month_start_checkin',
    icon: '🗓️',
    rarity: E,
    thresholds: [12],
    hidden: true,
    ru: ['С первым числом', 'Чек-инов первого числа месяца: {n}.'],
    en: ['Always on the first', 'Check-ins on the first day of a month: {n}.'],
  },
  {
    code: 'month_end',
    group: 'special',
    metric: 'special_month_end_checkin',
    icon: '🌇',
    rarity: R,
    thresholds: [1, 3, 6],
    hidden: true,
    ru: ['Конец месяца', 'Чек-инов в последний день месяца: {n}.'],
    en: ['End of the month', 'Check-ins on the last day of a month: {n}.'],
  },
  {
    code: 'month_end_pro',
    group: 'special',
    metric: 'special_month_end_checkin',
    icon: '🌙',
    rarity: E,
    thresholds: [12],
    hidden: true,
    ru: ['До последнего дня', 'Чек-инов в последний день месяца: {n}.'],
    en: ['Until the last day', 'Check-ins on the last day of a month: {n}.'],
  },
  {
    code: 'palindrome_day',
    group: 'special',
    metric: 'special_palindrome_checkin',
    icon: '🔁',
    rarity: L,
    thresholds: [1],
    hidden: true,
    ru: ['День-палиндром', 'Чек-ин в дату, которая читается одинаково в обе стороны.'],
    en: ['Palindrome day', 'A check-in on a date that reads the same both ways.'],
  },
  {
    code: 'halloween',
    group: 'special',
    metric: 'special_halloween_checkin',
    icon: '🎃',
    rarity: E,
    thresholds: [1],
    hidden: true,
    ru: ['Хэллоуин', 'Чек-ин 31 октября.'],
    en: ['Halloween', 'A check-in on October 31.'],
  },
];

function buildDefinition(row: Row, index: number): AchievementDefinition {
  const levels = LEVEL_SETS[row.thresholds.length];
  if (!levels) throw new Error(`achievement ${row.code}: недопустимое число уровней`);
  return {
    code: row.code,
    group: row.group,
    metric: row.metric,
    icon: row.icon,
    rarity: row.rarity,
    hidden: row.hidden ?? false,
    tiers: row.thresholds.map((threshold, i) => ({ level: levels[i]!, threshold })),
    titleKey: `achievements.${row.code}.title`,
    descriptionKey: `achievements.${row.code}.description`,
    position: index + 1,
  };
}

/** Каталог в порядке показа. */
export const ACHIEVEMENT_CATALOG: readonly AchievementDefinition[] = ROWS.map(buildDefinition);

/** Алиас прежнего имени каталога. */
export const ACHIEVEMENTS = ACHIEVEMENT_CATALOG;

export const ACHIEVEMENT_CODES: readonly AchievementCode[] = ACHIEVEMENT_CATALOG.map(
  (item) => item.code,
);

/** Тексты достижения по локали (без подстановки порога). */
export const ACHIEVEMENT_TEXTS: Readonly<Record<string, Record<Locale, AchievementText>>> =
  Object.fromEntries(
    ROWS.map((row) => [
      row.code,
      {
        ru: { title: row.ru[0], description: row.ru[1] },
        en: { title: row.en[0], description: row.en[1] },
      },
    ]),
  );

/** Словарь i18n-ключей достижений для подмешивания в словарь веба. */
export function achievementMessages(locale: Locale): Record<string, string> {
  const messages: Record<string, string> = {};
  for (const row of ROWS) {
    const text = row[locale];
    messages[`achievements.${row.code}.title`] = text[0];
    messages[`achievements.${row.code}.description`] = text[1];
  }
  return messages;
}

/** Описание достижения по коду. */
export function achievementByCode(code: AchievementCode): AchievementDefinition | undefined {
  return ACHIEVEMENT_CATALOG.find((item) => item.code === code);
}

/** Название достижения для сообщений вне веба (уведомления, карточки). */
export function achievementTitle(code: AchievementCode, locale: Locale = 'ru'): string {
  return ACHIEVEMENT_TEXTS[code]?.[locale].title ?? code;
}

/** Описание с подставленным порогом уровня. */
export function achievementDescription(
  code: AchievementCode,
  threshold: number,
  locale: Locale = 'ru',
): string {
  return (ACHIEVEMENT_TEXTS[code]?.[locale].description ?? code).replace('{n}', String(threshold));
}

/** Уровни, пороги которых достигнуты значением метрики. */
export function reachedTiers(definition: AchievementDefinition, value: number): AchievementTier[] {
  return definition.tiers.filter((tier) => value >= tier.threshold);
}

export interface AchievementProgress {
  /** Высший полученный уровень или null. */
  level: AchievementLevel | null;
  /** Следующий непройденный уровень или null, если всё получено. */
  next: AchievementTier | null;
  /** Доля пути до следующего порога (от порога предыдущего уровня), 0..1; 1 — всё получено. */
  progress: number;
}

/** Прогресс по значению метрики: текущий уровень, следующий порог и доля пути. */
export function progressFor(definition: AchievementDefinition, value: number): AchievementProgress {
  const reached = reachedTiers(definition, value);
  const level = reached.length > 0 ? reached[reached.length - 1]!.level : null;
  const next = definition.tiers.find((tier) => value < tier.threshold) ?? null;
  if (!next) return { level, next: null, progress: 1 };
  const base = reached.length > 0 ? reached[reached.length - 1]!.threshold : 0;
  const span = next.threshold - base;
  const done = Math.max(0, value - base);
  return { level, next, progress: span > 0 ? Math.min(1, done / span) : 0 };
}
